idle:
#Amount of time (in minutes) Legacy waits before marking a player AFK
  timeout: 15
auto-save:
#Amount of time (in minutes) Legacy waits to save data to log.yml
  frequency: 2
top:
#Number of players displayed when using /legacy top
  players: 10

#Please don't touch the version number :)
version: 1.0